export const FETCH_GIGS_REQUEST = 'FETCH_GIGS_REQUEST';
export const FETCH_GIGS_SUCCESS = 'FETCH_GIGS_SUCCESS';
export const FETCH_GIGS_FAILED = 'FETCH_GIGS_FAILED';

export const FETCH_GIGS_ADDITIONAL_DETAIL_REQUEST = 'FETCH_GIGS_ADDITIONAL_DETAIL_REQUEST';
export const FETCH_GIGS_ADDITIONAL_DETAIL_SUCCESS = 'FETCH_GIGS_ADDITIONAL_DETAIL_SUCCESS';
export const FETCH_GIGS_ADDITIONAL_DETAIL_FAILED = 'FETCH_GIGS_ADDITIONAL_DETAIL_FAILED';

export function fetchGigs() {
	return {
		type: FETCH_GIGS_REQUEST
	};
}

export function fetchGigsAdditionalDetail() {
	return {
		type: FETCH_GIGS_ADDITIONAL_DETAIL_REQUEST
	};
}